### ISSUE TITLE
How to use the handbook

### ISSUE THREAD

**Issue by karinlag** [NorwegianVeterinaryInstitute/ORION_HandBook#1]
Could @ajkarloss  create a one-page how-to for:

1. adding a completely new page
2. modifying an existing page

**Comment by ajkarloss** [comment]
The page HowToDo is coming up
https://orion-ngs-handbook.readthedocs.io/en/latest/howtodo.html

**Comment by karinlag** [comment]
Thanks, will test this out a bit later today, I hope.

I however think we should use the pull request workflow. Could you, @ajkarloss add that to the doc?

**Comment by karinlag** [comment]
Just noticed I don't quite get steps 3 and 4 under the rebuild, specifically the words connect and build, could that be expanded on?

**Comment by ajkarloss** [comment]
I agree. It's quit tough to explain. My plan is to give a demo to you all.

**Comment by karinlag** [comment]
Great, and thanks! Could you talk to Thomas and find a time for us next week? Thurs and Fri are good for me 🙂

**Comment by ajkarloss** [comment]
Friday is good for me. I will ask Thomas also. Any time preferences?

**Comment by karinlag** [comment]
Not during cake, otherwise anytime is good for me. Thomas might have preferences?

**Comment by Thomieh73** [comment]
Friday would be good too.

**Comment by ajkarloss** [comment]
Thomas is also fine. Lets say we meet at 12.30pm.
