### ISSUE TITLE
Create a CONTRIBUTING document (not just technical but also social)

### ISSUE THREAD

**Issue by karinlag** [NorwegianVeterinaryInstitute/ORION_HandBook#3]
Inspiration from here:

https://github.com/swcarpentry/shell-novice/blob/gh-pages/CONTRIBUTING.md

**Comment by karinlag** [comment]
Working on it here:

https://docs.google.com/document/d/1pOk6qirmcdUX3XSzuyGtrtswMS93cYroFKUCRYPv63I/edit

We need to figure out some details about it, the main part is how we ask other to contribute. I am detailing @ajkarloss on that part.

**Comment by karinlag** [comment]
could @ajkarloss and @Thomieh73 have a readthrough when they have time? if it looks good to both ofyou,  @ajkarloss can move it to the handbook itself, and then close the issue.

**Comment by ajkarloss** [comment]
Looks good for me

**Comment by Thomieh73** [comment]
I also think it looks good and clear.

**Comment by karinlag** [comment]
I just realized that we should include instructions on how to include a new page, and if so, how to get it into the toc in a good way. @ajkarloss could you include that at the bottom?

**Comment by karinlag** [comment]
I have finished the docs, IMO, just need to get them into master. 

https://docs.google.com/document/d/1pOk6qirmcdUX3XSzuyGtrtswMS93cYroFKUCRYPv63I/edit#

Have added the Code of Conduct there too.

**Comment by karinlag** [comment]
I think this one is done. Can @Thomieh73 and @ajkarloss read through this by the 22nd of May and leave comments on this one here?

**Comment by karinlag** [comment]
Has been completed. Clsoing.
