### ISSUE TITLE
We need a license

### ISSUE THREAD

**Issue by karinlag** [NorwegianVeterinaryInstitute/ORION_HandBook#4]
I am attempting to see if we can use this text:

https://github.com/swcarpentry/shell-novice/blob/gh-pages/LICENSE.md

**Comment by karinlag** [comment]
I have clarified with the carpentries that this text is from here:

https://creativecommons.org/licenses/by/4.0/

Thus we can grab that and use it. 

Once we have the structure in place as per #8 we will add it.

**Comment by karinlag** [comment]
@karinlag or @ajkarloss need to put the license on the readthedocs site too.

**Comment by ajkarloss** [comment]
DONE
